DAET: use case statements

diff --git a/DAET b/DAET
--- a/DAET
+++ b/DAET
@@ -1,3 +1,5 @@
+#!/bin/bash
+
  #
  # Copyright (C) 2012-2013, Ayysir
  #
@@ -12,22 +14,59 @@
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
- #
- 
- 
+ # 
+
+
+while :
+do
+    UB="`pwd`/scripts/ubuntu"
+
+    if [ "$ERROR" != "" ]; then
+    echo "Error: $ERROR"
+    echo ""
+    fi
+
     echo  "Main Menu"
-    echo  "a. Archlinux Setup"
-    echo  "u. Ubuntu Setup" 
-    echo  "n. Update Scripts" 
+    echo  " ------- "
+    echo  "1. Ubuntu Setup"
+    echo  "2. Archlinux Setup" 
+    echo  "3. Update Scripts" 
+    echo  "0. Exit"
     echo  "Enter your choice " 
+    ERROR=""
     read input
 
-    if   [[ $input == 'a' || $input == 'A' ]]; then
-      echo "al"
-    elif [[ $input == 'u' || $input == 'U' ]]; then
-      echo "ub"
-    elif [[ $input == 'n' || $input == 'N' ]]; then
-      echo "upd"
-    else 
-      echo "yolo"	
-    fi
+    case $input in
+      1)
+            if [ -f $UB ]; then
+                echo "it exists"
+              else
+                      echo "File does not exist"
+              fi
+              ;;
+      2)
+            if [[ -f `pwd`/scripts/arch ]]; then
+               source /scripts/arch
+              else
+                      echo "File does not exist"
+              fi
+              ;;
+      3)
+            if [[ -f `pwd`/scripts/update ]]; then
+               source /scripts/update
+              else
+                      echo "File does not exist"
+              fi
+              ;;
+
+      0)
+          reset 
+          exit 1
+          ;;
+
+      *)
+            ERROR="Please enter a valid option"
+    esac
+
+            clear
+done
